### PR TITLE
gmenu: Fix out-of-range value crashes

### LINKED ISSUE #615: v25: Settings window won't open, tracebacks in gmenu.js
With v25 under GNOME Shell 3.32.2 (and possibly other releases), the Mobile Settings window may fail to open. A traceback similar to the following will appear in the user journal:

```
Sep 10 07:02:01 gnome-shell[2322]: value "-1.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: == Stack trace for context 0x56297bfd2310 ==
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #0   5629879349d8 i   /home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:139 (7fcb5cb920d0 @ 70)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #1   7ffc1dfba7a0 b   self-hosted:979 (7fcb6c2515e0 @ 440)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #2   562987934940 i   resource:///org/gnome/shell/ui/boxpointer.js:99 (7fcb6c20dee0 @ 112)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #3   5629879348a8 i   resource:///org/gnome/shell/ui/boxpointer.js:180 (7fcb6c212160 @ 12)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #4   562987934820 i   resource:///org/gnome/shell/ui/tweener.js:85 (7fcb6c6c88b0 @ 37)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #5   7ffc1dfbfbc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (7fcb6c6d14c0 @ 54)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #6   7ffc1dfbfd10 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:342 (7fcb6c6d1550 @ 1742)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #7   7ffc1dfbfdc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:355 (7fcb6c6d15e0 @ 100)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #8   7ffc1dfbfe50 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:370 (7fcb6c6d1670 @ 10)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #9   7ffc1dfbfed0 I   resource:///org/gnome/gjs/modules/signals.js:142 (7fcb6c6cb670 @ 386)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #10   7ffc1dfbff80 b   resource:///org/gnome/shell/ui/tweener.js:201 (7fcb6c6cb160 @ 159)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #11   7ffc1dfc0020 b   resource:///org/gnome/shell/ui/tweener.js:172 (7fcb6c6cb040 @ 15)
```

This is fixed in PR #614

### PR DESCRIPTION
**Pull request by ferdnyc**
v25 release under 3.32.2 was failing to open the settings window, due to an out-of-range value in `gmenu.js`. 

Traceback:
```
Sep 10 07:02:01 gnome-shell[2322]: value "-1.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: == Stack trace for context 0x56297bfd2310 ==
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #0   5629879349d8 i   /home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:139 (7fcb5cb920d0 @ 70)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #1   7ffc1dfba7a0 b   self-hosted:979 (7fcb6c2515e0 @ 440)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #2   562987934940 i   resource:///org/gnome/shell/ui/boxpointer.js:99 (7fcb6c20dee0 @ 112)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #3   5629879348a8 i   resource:///org/gnome/shell/ui/boxpointer.js:180 (7fcb6c212160 @ 12)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #4   562987934820 i   resource:///org/gnome/shell/ui/tweener.js:85 (7fcb6c6c88b0 @ 37)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #5   7ffc1dfbfbc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (7fcb6c6d14c0 @ 54)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #6   7ffc1dfbfd10 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:342 (7fcb6c6d1550 @ 1742)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #7   7ffc1dfbfdc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:355 (7fcb6c6d15e0 @ 100)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #8   7ffc1dfbfe50 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:370 (7fcb6c6d1670 @ 10)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #9   7ffc1dfbfed0 I   resource:///org/gnome/gjs/modules/signals.js:142 (7fcb6c6cb670 @ 386)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #10   7ffc1dfbff80 b   resource:///org/gnome/shell/ui/tweener.js:201 (7fcb6c6cb160 @ 159)
Sep 10 07:02:01 org.gnome.Shell.desktop[2322]: #11   7ffc1dfc0020 b   resource:///org/gnome/shell/ui/tweener.js:172 (7fcb6c6cb040 @ 15)
```

Fixes #615

### CODE REVIEW

**Comment by ferdnyc** [comment]
I added a second commit to squash a Travis "unnecessary escapes" failure in the `__common_name` regexp.

File: src/shell/gmenu.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ var ListBox = class ListBox extends PopupMenu.PopupMenuSection {
         // We use this instead of close() to avoid touching finalized objects
         } else {
             this.box.opacity = 255;
-            this.box.width = -1;
+            this.box.width = 0;
```
Comment (andyholmes) [inline src/shell/gmenu.js]: Hmm, this seems to work, although it sort of shouldn't :P 

The mistake I made here was thinking `-1` meant "go back to deciding your own allocation", which is what it does in Gtk. I now see `ClutterActor` has different properties for `width`, `natural-width` and `natural-width-set`. I'll merge this since it works, but we should keep an eye on this.

Comment (ferdnyc) [reply src/shell/gmenu.js]: I guess `this.box.x_expand` in the constructor is what probably saves it. (And, perhaps, is also why there's no real point in touching the `width` here at all? Setting it may do literally nothing.)

Comment (andyholmes) [reply src/shell/gmenu.js]: Figured it out. I was using the property accessors instead of the property methods, which do take `-1` to reset the preferred size.

Comment (ferdnyc) [reply src/shell/gmenu.js]: Oh, sure. That makes sense.

(THAT WAS SARCASM, BECAUSE IT MAKES NO SENSE AT ALL. COULD YOU TELL I WAS BEING SARCASTIC? :wink: )
